'use server';

import { createActionSupabaseClient } from '../supabase-server';
import { revalidatePath } from 'next/cache';

export async function generateAIQuiz(topic: string, context?: string) {
  const supabase = createActionSupabaseClient();
  const { data: { session } } = await supabase.auth.getSession();
  
  if (!session) throw new Error('Unauthorized');

  try {
    // Ensure profile exists (safety check for FK constraint)
    const { data: profile } = await supabase
      .from('profiles')
      .select('id')
      .eq('id', session.user.id)
      .single();

    if (!profile) {
      await supabase.from('profiles').insert([{
        id: session.user.id,
        email: session.user.email,
        full_name: session.user.user_metadata?.full_name || 'Student User'
      }]);
    }

    const apiKey = process.env.GEMINI_API_KEY;
    let questions = [];

    if (apiKey) {
      const prompt = `You are an expert academic examiner. Generate a high-quality multiple choice quiz.
      Topic: ${topic}
      ${context ? `Context/Notes: ${context}` : ''}
      
      Requirements:
      1. Generate 5 challenging questions.
      2. Each question must have 4 options.
      3. Provide the correct answer (index 0-3).
      4. Provide a 1-sentence explanation for the correct answer.
      5. Response must be a JSON array of objects:
      [
        {
          "question": "string",
          "options": ["string", "string", "string", "string"],
          "correctAnswer": number,
          "explanation": "string"
        }
      ]
      Return ONLY the JSON array.`;

      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 25000);

      const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] }),
        signal: controller.signal
      });
      
      clearTimeout(timeoutId);
      
      if (!res.ok) throw new Error(`Gemini API Error: ${res.status}`);

      const responseData = await res.json();
      const rawText = responseData.candidates?.[0]?.content?.parts?.[0]?.text;
      
      if (!rawText) throw new Error("AI failed to generate quiz content.");

      const aiText = rawText.replace(/```json/g, '').replace(/```/g, '').trim();
      questions = JSON.parse(aiText);
    } else {
      throw new Error("AI Configuration Missing (API Key).");
    }

    if (!Array.isArray(questions) || questions.length === 0) {
      throw new Error("Invalid quiz data generated by AI.");
    }

    const { data, error } = await supabase
      .from('quizzes')
      .insert([{
        user_id: session.user.id,
        topic,
        questions,
        difficulty: 'Medium'
      }])
      .select();

    if (error || !data || data.length === 0) {
      console.error('Quiz Database Insert Error:', error);
      throw new Error(error?.message || "Failed to save quiz to database.");
    }

    revalidatePath('/dashboard/quizzes');
    return { success: true, data: data[0] };

  } catch (error: any) {
    console.error('Quiz Generation Error:', error);
    return { success: false, error: error.message };
  }
}

export async function saveQuizResult(quizId: string, score: number) {
  const supabase = createActionSupabaseClient();
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) throw new Error('Unauthorized');

  const { error } = await supabase
    .from('quizzes')
    .update({ score })
    .eq('id', quizId)
    .eq('user_id', session.user.id);

  if (error) throw error;
  
  revalidatePath('/dashboard/quizzes');
  revalidatePath('/dashboard');
  return { success: true };
}

export async function getUserQuizzes() {
  const supabase = createActionSupabaseClient();
  try {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) return { success: false, error: 'Unauthorized' };

    const { data, error } = await supabase
      .from('quizzes')
      .select('*')
      .eq('user_id', session.user.id)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return { success: true, data: data || [] };
  } catch (error: any) {
    return { success: false, error: error.message };
  }
}
